name: Unit tests

on:
  push:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: python -m unittest orig/unit_testing/test_math_lib.py

  run_pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          init-shell: bash
      - run: pycodestyle orig/unit_testing/test_math_lib.py
        shell: bash -l {0}